version: "2.7"

server:
  command: "php vendor/bin/rr-worker start"

http:
  address: 127.0.0.1:8000
  middleware: ["static", "headers", "gzip"]
  pool:
    max_jobs: 64 # feel free to change this
    supervisor:
      exec_ttl: 60s
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [".php"]
